version: "3.9"

services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app/apps/backend

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    working_dir: /app/apps/frontend